module.exports = {
  __init__: [
    'tokenSimulationBehavior',
    'contextMenu',
    'animation',
    'globalReset',
    'tokenDisplay',
    'gatewayConfiguration',
    'checkGatewayConfiguration',
    'notifications',
    'catchEventTrigger',
    'simulationState',
    'tokenGraphics',
    'log',
    'playPause',
    'contextMenuPreview',
    'checkElementSupport',
    'switchMode',
    'readOnly',
    'tokenSimulationEditorActions'
  ],
  'tokenSimulationBehavior': [ 'type', require('./TokenSimulationBehavior') ],
  'contextMenu': [ 'type', require('./ContextMenu') ],
  'animation': [ 'type', require('./Animation') ],
  'globalReset': [ 'type', require('./GlobalReset') ],
  'tokenDisplay': [ 'type', require('./TokenDisplay') ],
  'gatewayConfiguration': [ 'type', require('./GatewayConfiguration') ],
  'checkGatewayConfiguration': [ 'type', require('./CheckGatewayConfiguration') ],
  'notifications': [ 'type', require('./Notifications') ],
  'catchEventTrigger': [ 'type', require('./CatchEventTrigger')],
  'simulationState': [ 'type', require('./SimulationState')],
  'tokenGraphics': [ 'type', require('./TokenGraphics')],
  'playPause': [ 'type', require('./PlayPause')],
  'log': [ 'type', require('./Log') ],
  'contextMenuPreview': [ 'type', require('./ContextMenuPreview') ],
  'checkElementSupport': [ 'type', require('./CheckElementSupport') ],
  'switchMode': [ 'type', require('./SwitchMode') ],
  'readOnly': [ 'type', require('./ReadOnly') ],
  'tokenSimulationEditorActions': [ 'type', require('./EditorActions') ]
};
