module.exports = {
  __init__: [
    'animation',
    'contextPads',
    'disableModeling',
    'elementNotifications',
    'elementSupport',
    'exclusiveGatewaySettings',
    'keyboardBindings',
    'log',
    'notifications',
    'pauseSimulation',
    'resetSimulation',
    'simulationState',
    'toggleMode',
    'tokenCount',
    'tokenSimulationBehavior',
    'tokenSimulationEditorActions',
    'tokenSimulationPalette'
  ],
  'animation': [ 'type', require('./animation/Animation') ],
  'contextPads': [ 'type', require('./features/context-pads') ],
  'disableModeling': [ 'type', require('./features/disable-modeling') ],
  'elementNotifications': [ 'type', require('./features/element-notifications') ],
  'elementSupport': [ 'type', require('./features/element-support') ],
  'exclusiveGatewaySettings': [ 'type', require('./features/exclusive-gateway-settings') ],
  'keyboardBindings': [ 'type', require('./features/keyboard-bindings/modeler') ],
  'log': [ 'type', require('./features/log') ],
  'notifications': [ 'type', require('./features/notifications') ],
  'pauseSimulation': [ 'type', require('./features/pause-simulation') ],
  'resetSimulation': [ 'type', require('./features/reset-simulation') ],
  'simulationState': [ 'type', require('./features/simulation-state') ],
  'toggleMode': [ 'type', require('./features/toggle-mode/modeler') ],
  'tokenCount': [ 'type', require('./features/token-count') ],
  'tokenSimulationBehavior': [ 'type', require('./features/token-simulation-behavior') ],
  'tokenSimulationEditorActions': [ 'type', require('./features/editor-actions') ],
  'tokenSimulationPalette': [ 'type', require('./features/palette') ]
};