module.exports = {
  __init__: [
    'animation',
    'contextPads',
    'disableModeling',
    'elementNotifications',
    'elementSupport',
    'exclusiveGatewaySettings',
    'log',
    'notifications',
    'pauseSimulation',
    'preserveElementColors',
    'processInstanceIds',
    'processInstanceSettings',
    'processInstances',
    'resetSimulation',
    'setAnimationSpeed',
    'showProcessInstance',
    'simulationState',
    'toggleMode',
    'tokenCount',
    'tokenSimulationBehavior',
    'tokenSimulationEditorActions',
    'tokenSimulationKeyboardBindings',
    'tokenSimulationPalette'
  ],
  'animation': [ 'type', require('./animation/Animation') ],
  'contextPads': [ 'type', require('./features/context-pads') ],
  'disableModeling': [ 'type', require('./features/disable-modeling') ],
  'elementNotifications': [ 'type', require('./features/element-notifications') ],
  'elementSupport': [ 'type', require('./features/element-support') ],
  'exclusiveGatewaySettings': [ 'type', require('./features/exclusive-gateway-settings') ],
  'log': [ 'type', require('./features/log') ],
  'notifications': [ 'type', require('./features/notifications') ],
  'pauseSimulation': [ 'type', require('./features/pause-simulation') ],
  'preserveElementColors': [ 'type', require('./features/preserve-element-colors') ],
  'processInstanceIds': [ 'type', require('./features/process-instance-ids') ],
  'processInstanceSettings': [ 'type', require('./features/process-instance-settings') ],
  'processInstances': [ 'type', require('./features/process-instances') ],
  'resetSimulation': [ 'type', require('./features/reset-simulation') ],
  'setAnimationSpeed': [ 'type', require('./features/set-animation-speed') ],
  'showProcessInstance': [ 'type', require('./features/show-process-instance') ],
  'simulationState': [ 'type', require('./features/simulation-state') ],
  'toggleMode': [ 'type', require('./features/toggle-mode/modeler') ],
  'tokenCount': [ 'type', require('./features/token-count') ],
  'tokenSimulationBehavior': [ 'type', require('./features/token-simulation-behavior') ],
  'tokenSimulationEditorActions': [ 'type', require('./features/editor-actions') ],
  'tokenSimulationKeyboardBindings': [ 'type', require('./features/keyboard-bindings') ],
  'tokenSimulationPalette': [ 'type', require('./features/palette') ]
};