module.exports = {
  __depends__: [
    require('./simulator').default,
    require('./animation').default,
    require('./features/colored-scopes').default,
    require('./features/context-pads').default,
    require('./features/simulation-state').default,
    require('./features/show-scopes').default
  ],
  __init__: [
    'disableModeling',
    'elementNotifications',
    'elementSupport',
    'exclusiveGatewaySettings',
    'log',
    'notifications',
    'pauseSimulation',
    'preserveElementColors',
    'processInstanceIds',
    'processInstanceSettings',
    'processInstances',
    'resetSimulation',
    'setAnimationSpeed',
    'toggleMode',
    'tokenCount',
    'tokenSimulationEditorActions',
    'tokenSimulationKeyboardBindings',
    'tokenSimulationPalette'
  ],
  'disableModeling': [ 'type', require('./features/disable-modeling') ],
  'elementNotifications': [ 'type', require('./features/element-notifications').default ],
  'elementSupport': [ 'type', require('./features/element-support') ],
  'exclusiveGatewaySettings': [ 'type', require('./features/exclusive-gateway-settings') ],
  'log': [ 'type', require('./features/log').default ],
  'notifications': [ 'type', require('./features/notifications').default ],
  'pauseSimulation': [ 'type', require('./features/pause-simulation').default ],
  'preserveElementColors': [ 'type', require('./features/preserve-element-colors').default ],
  'processInstanceIds': [ 'type', require('./features/process-instance-ids') ],
  'processInstanceSettings': [ 'type', require('./features/process-instance-settings') ],
  'processInstances': [ 'type', require('./features/process-instances') ],
  'resetSimulation': [ 'type', require('./features/reset-simulation').default ],
  'setAnimationSpeed': [ 'type', require('./features/set-animation-speed').default ],
  'toggleMode': [ 'type', require('./features/toggle-mode/modeler') ],
  'tokenCount': [ 'type', require('./features/token-count').default ],
  'tokenSimulationEditorActions': [ 'type', require('./features/editor-actions') ],
  'tokenSimulationKeyboardBindings': [ 'type', require('./features/keyboard-bindings') ],
  'tokenSimulationPalette': [ 'type', require('./features/palette') ]
};